name: Deploy Django App

on:
  push:
    branches:
      - main


jobs:
  # =========================
  # 1. TEST JOB (CI GATE)
  # =========================
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # Check Python or install
      # -------------------------
      - name: Check Python installation
        run: |
          if command -v python3 &> /dev/null
          then
              echo "✅ Python is installed"
              python3 --version
          else
              echo "❌ Python not found. Installing..."
              sudo apt update
              sudo apt install python3 python3-pip -y
          fi

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------
      # Run tests
      # -------------------------
      - name: Run Pytest
        run: |
          pytest -x --disable-warnings --maxfail=1


  # =========================
  # 2. DEPLOY JOB
  # =========================
  deploy:
    needs: test   # 👈 runs ONLY if tests pass
    runs-on: self-hosted

    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.90.3.101 << 'EOF'

            set -e

            cd cd-cd-practice

            git pull origin main

            # Optional (if using docker)
            # docker compose up -d --build

            # Optional (if Django server)
            # sudo systemctl restart gunicorn
            # sudo systemctl restart nginx

          EOF

      - name: Notify Success
        run: echo "🚀 Deployment Successful!"