name: Deploy Django App

on:
  push:
    branches:
      - main


jobs:
  # =========================
  # 1. TEST JOB (CI GATE)
  # =========================
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # Install Python + pip
      # -------------------------
      - name: Setup Python & Pip
        run: |
          sudo apt update

          # Install Python if missing
          if ! command -v python3 &> /dev/null; then
              sudo apt install python3 -y
          fi

          # Install pip if missing
          if ! command -v pip3 &> /dev/null; then
              sudo apt install python3-pip -y
          fi

          python3 --version
          pip3 --version

      # -------------------------
      # Create virtual environment
      # -------------------------
      - name: Create Virtual Environment
        run: |
          sudo apt install python3-venv -y
          python3 -m venv venv
          source venv/bin/activate

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------
      # Run tests
      # -------------------------
      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest -x --disable-warnings --maxfail=1


  # =========================
  # 2. DEPLOY JOB
  # =========================
  deploy:
    needs: test   # 👈 ONLY RUNS IF TEST PASSES
    runs-on: self-hosted

    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.90.3.101 << 'EOF'

            set -e

            cd cd-cd-practice

            git pull origin main

            # Optional (Django production restart)
            # sudo systemctl restart gunicorn
            # sudo systemctl restart nginx

          EOF

      - name: Notify Success
        run: echo "🚀 Deployment Successful!"